### ISSUE TITLE
Insulate Molding Barrel template

### ISSUE THREAD

**Issue by BrushXue** [LehighIAC/IAC-Automation#30]

**Comment by BrushXue** [comment]
Please repair this part
<img width="695" alt="Screen Shot 2024-03-07 at 12 16 53 PM" src="https://github.com/LehighIAC/IAC-Automation/assets/12702149/dae22416-ab26-4f28-b04a-8bf094374058">

**Comment by BrushXue** [comment]
To simplify automation, use IC=Σ(Ai*unit_price_i)

**Comment by AlexGuataipu** [comment]
Corrected automation as mentioned
