### ISSUE TITLE
Operating hours abbreviation

### ISSUE THREAD

**Issue by BrushXue** [LehighIAC/IAC-Automation#38]
![Screenshot 2024-03-21 123325](https://github.com/LehighIAC/IAC-Automation/assets/12702149/2fd21c7a-32ec-4d50-bc6a-71add39a8c1f)

1. change `hour` to `hr`, `week` to `wk` and `year` to `yr`. don't change`day`. Change all applicable templates.
2. for multi-line equations, the second line should be aligned to the first line like the picture. Change all applicable templates.

**Comment by AlexGuataipu** [comment]
All templates were updated to follow this format (hrs/day, days/wk, wks/yr) and aligned to the equal sign. The equal sign is more consistent and doesn't mess with formatting of the template
